### ISSUE TITLE
Handle more gracefully non-supported path syntax by Pandoc on Windows

### ISSUE THREAD

**Issue by olivroy** [cderv/pandoc#31] opened 2023-06-08 13:49 UTC
Hi,
thanks for the great package.

On windows, using 
```r
pandoc::pandoc_convert(file = "~/../file.ext")
! Running Pandoc failed with following error
• pandoc.exe: ~/../file.ext withBinaryFile: does not exist (No such file or directory)
doesn't work.
```

I have to use (and it works)
```r
pandoc::pandoc_convert(file = normalizePath("~/../file.ext"))
```

Maybe R could process first if the file exists before trying to run pandoc.

Also path with space doesn't work (no way to fix this other than to rename the file

```r
pandoc::pandoc_convert(file = "~/../file with space.ext")
! Running Pandoc failed with following error
• pandoc.exe: ~/../file withBinaryFile: does not exist (No such file or directory)
doesn't work.
```
(Notice the absence of the rest of the file name in the error message)

Thanks!
Running with latest R package version and pandoc 3.1.1

**Comment by cderv** [comment] 2023-06-09 11:01
Those are Pandoc errors. 🤔 

> Maybe R could process first if the file exists before trying to run pandoc.

In first case we can indeed resolve the path and normalize. I think this would work and have no issue. I just don't want to use absolute path everywhere though just to handle this specific syntax `~/..` that Pandoc path resolver does not handle. (possilbly a Pandoc issue in the first place

> Also path with space doesn't work (no way to fix this other than to rename the file

The example you gave has also the other issue above. So is this link to the other issue ? Or do file with spaces not work at all, even when the path is not using the specific `~/..` syntax ? 

It could be a quoting issue also when passing the file path as argument from R to `pandoc` command line

**Comment by cderv** [comment] 2023-06-09 13:11
Thanks for testing ! 

I'll do the tweak for the resolving looking at how  **rmarkdown** does it. 

For the space, it seems an issue really in this package and quoting for the pandoc CLI as it seems to work with Pandoc CLI directly

````powershell
> cd $env:TEMP
> echo "# test" > 'file with space.ext'
> cat '.\file with space.ext'
# test
> pandoc -t html '.\file with space.ext'
[WARNING] Could not deduce format from file extension .ext
  Defaulting to markdown
<h1 id="test">test</h1>
> rm '.\file with space.ext'
> cd
````

**Closed** 2023-08-23 10:34 UTC
Labels: bug, feature, pandoc

**Comment by cderv** [comment] 2023-08-23 10:37
We now use `path.expand` to handle the `~`. 

Regarding the space, I think it is already working. I can't reproduce and I already have test for this which is passing
https://github.com/cderv/pandoc/blob/628302fc89553788bdee88d7dd35f06f1230010b/tests/testthat/test-pandoc-convert.R#L16-L26

Is this happening for you with a specific Pandoc version maybe  ? 

I am closing this as space in file is working for me. Please reopen or a new one with new information if something is still not working with dev version
